"""Capture the README screenshots (docs/screenshots/*.png) from the running app.

Dev-time tool, not part of the test suite. Requirements:
    pip install playwright && playwright install chromium
and a running app at http://127.0.0.1:8000 with APP_ACCESS_TOKEN in .env plus the
demo session (runs/api_bigtest0001, regenerated by the density demo script).

Usage:  python scripts/capture_docs_screenshots.py [--session api_bigtest0001]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from playwright.sync_api import sync_playwright

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "screenshots"
APP = "http://127.0.0.1:8000"

# 视口与旧图一致（1590×1466 ≈ 1440 视口 + 全页高度），保证 README 排版不变
VIEWPORT = {"width": 1440, "height": 1000}


def read_token() -> str:
    text = (REPO / ".env").read_text(encoding="utf-8", errors="ignore")
    match = re.search(r"^APP_ACCESS_TOKEN\s*=\s*(.+)$", text, re.MULTILINE)
    if not match:
        raise SystemExit("在 .env 里找不到 APP_ACCESS_TOKEN")
    return match.group(1).strip()


def launch(playwright, **kwargs):
    """优先用自带浏览器，缺失时退回本机已装的 Chromium。"""
    import glob
    import os

    try:
        return playwright.chromium.launch(**kwargs)
    except Exception as first_error:  # noqa: BLE001
        roots = [os.environ.get("PLAYWRIGHT_BROWSERS_PATH") or "",
                 str(Path.home() / "AppData" / "Local" / "ms-playwright"),
                 str(Path.home() / ".cache" / "ms-playwright")]
        for root in roots:
            if not root or not Path(root).is_dir():
                continue
            for pattern in ("chromium-*/chrome-win64/chrome.exe", "chromium-*/chrome-linux/chrome"):
                for candidate in sorted(glob.glob(str(Path(root) / pattern)), reverse=True):
                    try:
                        return playwright.chromium.launch(executable_path=candidate, **kwargs)
                    except Exception:  # noqa: BLE001
                        continue
        raise first_error


def open_session(page, session: str) -> None:
    page.keyboard.press("Control+k")
    page.wait_for_timeout(400)
    page.keyboard.type(session)
    page.wait_for_timeout(1200)
    page.keyboard.press("Enter")
    page.wait_for_timeout(3500)


def click_tab(page, name: str) -> None:
    page.evaluate(
        """(label) => { const t = Array.from(document.querySelectorAll('button,[role=tab],a'))
                        .find(el => (el.textContent || '').includes(label));
                       if (t) t.click(); }""",
        name,
    )
    page.wait_for_timeout(2500)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--session", default="api_bigtest0001")
    args = parser.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    token = read_token()
    with sync_playwright() as p:
        browser = launch(p)
        page = browser.new_page(viewport=VIEWPORT)
        page.goto(APP, wait_until="domcontentloaded")
        page.evaluate("(t) => localStorage.setItem('data-desk-access-token', t)", token)
        page.evaluate("() => localStorage.removeItem('data-desk-current-session')")
        page.reload(wait_until="networkidle")
        page.wait_for_timeout(2500)

        # 1) 起始页（浅色）：hero + 格式徽章 + 主 CTA
        page.screenshot(path=str(OUT / "start-light.png"))
        print("wrote start-light.png")

        # 2) 打开演示会话 → 分析页（浅色 / 暗色）
        open_session(page, args.session)
        click_tab(page, "分析")
        page.screenshot(path=str(OUT / "overview-light.png"), full_page=True)
        print("wrote overview-light.png")

        # 3) 数据页表格
        click_tab(page, "数据")
        page.wait_for_timeout(1500)
        page.screenshot(path=str(OUT / "data-preview.png"))
        print("wrote data-preview.png")

        # 4) 产物页（图表卡片 = 缩略图）
        #    缩略图是懒加载的，且**离开视口会被 purge**（useInView 释放实例），
        #    所以：① 不能用 full_page 截图（折叠线以下的卡片是空白）；
        #    ② 也不能中途改视口（ECharts 迷你画布不会跟着重绘，实测变空白）。
        #    做法是**一开始就用高视口打开一个新页面**，让 5 张卡片始终在场。
        tall = browser.new_page(viewport={"width": VIEWPORT["width"], "height": 1800})
        tall.goto(APP, wait_until="domcontentloaded")
        tall.evaluate("(t) => localStorage.setItem('data-desk-access-token', t)", token)
        tall.reload(wait_until="networkidle")
        tall.wait_for_timeout(2000)
        open_session(tall, args.session)
        click_tab(tall, "产物")
        tall.wait_for_timeout(5000)
        tall.screenshot(path=str(OUT / "artifacts-light.png"))
        print("wrote artifacts-light.png")
        tall.close()

        # 5) 图表预览（单面板密度图：边缘直方图 + 峰值标注 + 细节图层按钮）
        page.evaluate(
            """() => { const cards = Array.from(document.querySelectorAll('.chart-card'));
                       const target = cards.find(c => (c.textContent || '').includes('整体')) || cards[0];
                       const b = target && target.querySelector('.preview-button');
                       if (b) b.click(); }"""
        )
        page.wait_for_timeout(7000)
        page.screenshot(path=str(OUT / "preview-light.png"))
        print("wrote preview-light.png")
        page.keyboard.press("Escape")
        page.wait_for_timeout(1000)

        # 6) 暗色主题的同一页
        page.evaluate(
            """() => { const b = document.querySelector('button[title*="主题"], .theme-toggle, button[aria-label*="主题"]');
                       if (b) b.click(); }"""
        )
        page.wait_for_timeout(1500)
        click_tab(page, "分析")
        page.screenshot(path=str(OUT / "overview-dark.png"), full_page=True)
        print("wrote overview-dark.png")

        browser.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
